apiVersion: v1
kind: Pod
metadata:
  name: hacker-webapp
  namespace: dev-hackspace
  labels:
    environment: dev
    app: tomcat
    function: front-end
spec:
  containers:
  - name: devwebapp
    image: dockhubprivate.azurecr.io/webapp/tomcat_core:1.0.0
    imagePullPolicy: Always
    ports:
    - containerPort: 8080