apiVersion: v1
kind: Service
metadata:
  name: hacker-webapp-service
  namespace: dev-hackspace
spec:
  selector:
    app: tomcat
  ports:
   - protocol: TCP
     port: 8081
     targetPort: 8080
  type: LoadBalancer   
